# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import processor.models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='voice',
            field=models.FileField(upload_to=processor.models.upload_location),
        ),
    ]
