# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import processor.models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_auto_20170823_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('voice', models.FileField(upload_to=processor.models.temp_location)),
            ],
        ),
    ]
